[package]
name = "smbios"
version = "0.7.0"
authors = ["Jeffrey R. Gerber <jeffreygerber@gmail.com>, Ante Čulo <dante2711@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "SMBIOS Library"

# prevention from accidentally publishing
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "smbioslib"
path = "src/lib.rs"

[[bin]]
name = "smbiosdump"
path = "src/main.rs"

[dependencies]

[target.'cfg(windows)'.dependencies]
libc = "0.2"