[package]
name = "smbios"
version = "0.1.0"
authors = ["Jeff Gerber <jeffger@microsoft.com>"]
edition = "2018"
readme = "README.md"
description = "SMBIOS Library"

# prevention from accidentally publishing
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[target.'cfg(windows)'.dependencies]
libc = "0.2"