name: smbioslib_ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ labeled ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: ${{ github.event.label.name == 'Ready for Review' }} || github.event_name == 'push'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    # TODO: Also cross build for a platform that doesn't have std at all
    # Can only build the lib, not the tool as that needs std
    - name: Build with no_std support
      run: cargo build --lib --no-default-features --verbose
    - name: Run tests
      run: cargo test --verbose
